name: Compress Images

on:
  push:
    branches:
      - working
    paths:
      - 'frontend/images/**/*.{png,jpg,jpeg,webp,avif}'

jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compress images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # optional settings:
          jpegQuality: '85'
          pngQuality: '80'
          webpQuality: '80'
