name: Compress Images

# Run this workflow whenever pushed to any branch
on:
  push:
    branches:
      - working  # trigger on any push to working branch
      
jobs:
  compress-images:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v3

     
      - name: Compress images
        uses: tj-actions/compress-images@v4
        with:
          compress-level: 80  # adjust 0â€“100 quality (higher = better quality, larger size)
          include: 'frontend/src/assets/**/*.{png,jpg,jpeg}'
          exclude: ''          
